[package]
name = "AutoDoc"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
shaderpunk = { path = "../core" }
anyhow.workspace = true
argh.workspace = true
handlebars = "6.3"
serde.workspace = true
toml = "0.8"
vmap.workspace = true
